from .command import Command
from .command_manager import CommandManager

from .add_entity_command import AddEntityCommand
from .remove_entity_command import RemoveEntityCommand
from .move_entity_command import MoveEntityCommand
from .update_entity_command import UpdateEntityCommand, UpdateLayerCommand
from .macro_command import MacroCommand
from .trim_command import TrimEntityCommand, TrimCommand
from .extend_command import ExtendEntityCommand, ExtendCommand
from .offset_command import OffsetEntityCommand, OffsetCommand
from .rotate_command import RotateEntityCommand, RotateCommand
from .mirror_command import MirrorEntityCommand, MirrorCommand
from .scale_command import ScaleEntityCommand, ScaleCommand
from .copy_command import CopyEntityCommand, CopyCommand
from .array_command import ArrayEntityCommand, ArrayCommand
from .fillet_command import FilletEntityCommand, FilletCommand
from .chamfer_command import ChamferEntityCommand, ChamferCommand
from .block_command import (
    CreateBlockCommand,
    InsertBlockCommand,
    EditBlockCommand,
    ExplodeBlockCommand,
)
from .group_command import (
    CreateGroupCommand,
    DeleteGroupCommand,
    RenameGroupCommand,
    AddEntityToGroupCommand,
    RemoveEntityFromGroupCommand,
    UngroupCommand,
)
from .curve_command import UpdateCurveVerticesCommand, UpdatePolylineClosedCommand
from .primitive_command import CreatePrimitiveCommand
from .transform3d_command import (
    RotateEntity3DCommand,
    ScaleEntity3DCommand,
    TranslateEntity3DCommand,
    TransformEntity3DCommand,
)
from .measurement_command import AddMeasurementCommand, RemoveMeasurementCommand
from .section_command import (
    AddSectionPlaneCommand,
    RemoveSectionPlaneCommand,
    SetActiveSectionCommand,
    UpdateSectionPlaneCommand,
)
from .view_state_command import (
    DeleteViewStateCommand,
    RenameViewStateCommand,
    RestoreViewStateCommand,
    SaveViewStateCommand,
    SetDisplayModeCommand,
    SetVisualStyleCommand,
)
from .scene_organization_command import (
    AddViewFilterCommand,
    CreateSceneCollectionCommand,
    DeleteDisplayPresetCommand,
    DeleteSceneCollectionCommand,
    MoveEntityToCollectionCommand,
    RemoveViewFilterCommand,
    RenameDisplayPresetCommand,
    RenameSceneCollectionCommand,
    RestoreDisplayPresetCommand,
    SaveDisplayPresetCommand,
    UpdateSceneCollectionCommand,
)
from .annotation3d_command import (
    AddAnnotation3DCommand,
    AddReviewItemCommand,
    RemoveAnnotation3DCommand,
    RemoveReviewItemCommand,
    UpdateAnnotation3DCommand,
    UpdateReviewItemCommand,
)
from .collaboration_command import (
    AddIssueCommand,
    AddSessionCommand,
    ArchiveSessionCommand,
    DuplicateSessionCommand,
    RemoveIssueCommand,
    RestoreSessionCommand,
    UpdateIssueCommand,
    UpdateSessionCommand,
)
from .reference_command import (
    AddCoordinationRuleCommand,
    AddReferenceInstanceCommand,
    AddReferenceModelCommand,
    ImportReferenceCommand,
    ReloadReferenceCommand,
    ReloadImportedReferenceCommand,
    RemoveReferenceInstanceCommand,
    RemoveReferenceModelCommand,
    ReplaceReferenceCommand,
    SaveReferenceDisplayPresetCommand,
    SetReferenceIsolationCommand,
    UnloadReferenceCommand,
    UpdateCoordinationUICommand,
    UpdateReferenceLayerMappingCommand,
    UpdateReferenceInstanceCommand,
    UpdateReferenceModelCommand,
    UpdateReferenceStyleCommand,
)
from .clash_command import (
    AddClashResultCommand,
    LinkClashIssueCommand,
    LinkClashReviewCommand,
    RemoveClashResultCommand,
    RunClashDetectionCommand,
    SaveClashAnalyticsViewCommand,
    SaveClashDashboardFilterCommand,
    SaveClashDashboardLayoutCommand,
    UpdateClashAssignmentCommand,
    UpdateClashKPIConfigurationCommand,
    UpdateClashReportSettingsCommand,
    UpdateClashReportTemplateCommand,
    UpdateClashSettingsCommand,
    UpdateClashReviewCommand,
)
from .bcf_command import (
    AddBCFTopicCommand,
    ImportBCFProjectCommand,
    RemoveBCFTopicCommand,
    RestoreBCFViewpointCommand,
    UpdateBCFTopicCommand,
)
from .exchange_command import (
    SaveExchangeProfileCommand,
    StoreExchangeValidationReportCommand,
    UpdateExchangeSettingsCommand,
)
from .model_compare_command import (
    AddTimelineBookmarkCommand,
    CaptureRevisionCommand,
    CompareRevisionsCommand,
    CreateCompareSessionCommand,
    RemoveCompareSessionCommand,
    RunModelCompareCommand,
    UpdateCompareSettingsCommand,
    UpdateRevisionFiltersCommand,
)
from .coordination_package_command import (
    CreateCoordinationPackageCommand,
    RemoveCoordinationPackageCommand,
    UpdatePackagePreferencesCommand,
    ValidateCoordinationPackageCommand,
)
from .product_command import (
    ActivateSketchCommand,
    AddAINodeCommand,
    AddAssemblyComponentCommand,
    AddAssemblyConfigurationCommand,
    AddAssemblyMateCommand,
    AddAssemblyObjectCommand,
    AddBIMNodeCommand,
    AddCADNodeCommand,
    AddCAMObjectCommand,
    AddConstructionGeometryCommand,
    AddDataTreeCommand,
    AddDependencyGraphCommand,
    AddEdgeModificationCommand,
    AddExecutionObjectCommand,
    AddExplodedViewCommand,
    AddFeatureExecutionCommand,
    AddFeatureDependencyCommand,
    AddGeometryKernelCommand,
    AddLaserPlasmaObjectCommand,
    AddLiveSolverCommand,
    AddLivePreviewCommand,
    AddMachineLibraryObjectCommand,
    AddMechanicalLibraryCommand,
    AddManufacturingNodeCommand,
    AddManufacturingJobObjectCommand,
    AddManufacturingValidationCommand,
    AddNestingObjectCommand,
    AddParametricObjectCommand,
    AddParametricParameterCommand,
    AddPatternMetadataCommand,
    AddPostProcessorObjectCommand,
    AddProductAnalysisCommand,
    AddProductCurveCommand,
    AddProductBodyCommand,
    AddProductComponentCommand,
    AddProductFeatureCommand,
    AddProductMaterialCommand,
    AddProductMechanicalMetadataCommand,
    AddProductObjectCommand,
    AddProductParameterCommand,
    AddProductPartCommand,
    AddProductReportCommand,
    AddProductSketchCommand,
    AddProductValidationCommand,
    AddReferenceGeometryCommand,
    AddRouterObjectCommand,
    AddSheetMetalCommand,
    AddSheetMetalRuleCommand,
    AddScriptNodeCommand,
    AddSimulationObjectCommand,
    AddSlicerObjectCommand,
    AddSketchSolverCommand,
    AddSurfaceBodyCommand,
    AddSurfaceOperationCommand,
    AddThreeAxisCAMObjectCommand,
    AddToolLibraryCommand,
    AddVisualNodeGraphCommand,
    AddSketchConstraintCommand,
    AddSketchDimensionCommand,
    AddSketchGeometryCommand,
    ApplyProductFeatureCommand,
    AssignProductMaterialCommand,
    CreateProductDocumentCommand,
    CreateSolidFeatureCommand,
    DeactivateSketchCommand,
    EditProductFeatureCommand,
    ExecuteFeatureGeometryCommand,
    ExecuteProductFeatureMetadataCommand,
    PropagateProductUpdateCommand,
    RegenerateProductFeatureCommand,
    RenameProductFeatureCommand,
    RemoveProductObjectCommand,
    RollbackProductFeatureCommand,
    RollForwardProductFeaturesCommand,
    SuppressProductFeatureCommand,
    UpdateCAMOperationCommand,
)
from .ai_cad_command import AIParametricCADCommand
from .ai_platform_command import (
    AIInfrastructureCommand,
    CancelAITaskCommand,
    CaptureAIContextCommand,
    CaptureAIDiagnosticsCommand,
    CreateAISessionCommand,
    ResetAISessionCommand,
    RetryAIPromptCommand,
    SubmitAIPromptCommand,
    ValidateAIPromptCommand,
    ValidateAIProvidersCommand,
)
from .machine_cam_command import (
    CancelManufacturingJobCommand,
    CaptureMachineDiagnosticsCommand,
    CreateMachineProfileCommand,
    CreateManufacturingJobCommand,
    ExecuteManufacturingJobCommand,
    ExportManufacturingJobCommand,
    GenerateToolpathCommand,
    InitializeMachineCAMWorkspaceCommand,
    MachineCAMCommand,
    PauseManufacturingJobCommand,
    PostProcessManufacturingJobCommand,
    QueueManufacturingJobCommand,
    ResumeManufacturingJobCommand,
    SimulateManufacturingJobCommand,
)
from .bim_command import (
    AddBIMObjectCommand,
    AddBIMFamilyCommand,
    AddBIMElementDefinitionCommand,
    AddBIMPropertySetCommand,
    AddBIMTypeCommand,
    AddBIMAssemblyCommand,
    AddBIMMaterialCommand,
    AddBIMScheduleCommand,
    AddBIMSheetCommand,
    AddBIMViewCommand,
    AddBIMClassificationCommand,
    AddBIMConnectionCommand,
    AddBIMAreaAnalysisCommand,
    AddBIMAnnotationCommand,
    AddBIMConnectorCommand,
    AddBIMCoordinationReferenceCommand,
    AddBIMDesignOptionCommand,
    AddBIMDigitalTwinRecordCommand,
    AddBIMHostOpeningCommand,
    AddBIMIFCObjectCommand,
    AddBIMIntelligenceIssueCommand,
    AddBIMLifecycleCommand,
    AddBIMMEPCommand,
    AddBIMInteroperabilityCommand,
    AddBIMModelCheckCommand,
    AddBIMPhaseCommand,
    AddBIMRecommendationCommand,
    AddBIMRelationshipCommand,
    AddBIMReviewSessionCommand,
    AddBIMRuleCommand,
    AddBIMRoomCommand,
    AddBIMSpaceCommand,
    AddBIMValidationCommand,
    AddBIMZoneCommand,
    AssignBIMMaterialCommand,
    BuildBIMScheduleCommand,
    ArrayBIMElementCommand,
    ChangeBIMElementLevelCommand,
    ChangeBIMElementMaterialCommand,
    CertifyBIMCompatibilityCommand,
    CertifyBIMReleaseCommand,
    ConnectBeamToColumnCommand,
    ConnectColumnToFoundationCommand,
    CopyBIMElementCommand,
    CreateBeamCommand,
    CreateBIMDocumentationDocumentCommand,
    CreateBIMElementCommand,
    CreateBIMElementRelationshipCommand,
    CreateCeilingCommand,
    CreateColumnCommand,
    CreateCurtainWallCommand,
    CreateDoorCommand,
    CreateFloorFinishCommand,
    CreateRailingCommand,
    CreateRampCommand,
    CreateRoofCommand,
    CreateSlabCommand,
    CreateStairCommand,
    CreateWallCommand,
    CreateWindowCommand,
    CreateBIMProjectCommand,
    DeleteBIMElementCommand,
    EditBIMElementCommand,
    ExportIFC43Command,
    GenerateAIBIMRecommendationsCommand,
    GenerateBIMDrawingCommand,
    GenerateBIMScheduleCommand,
    HostDoorByWallCommand,
    HostWindowByWallCommand,
    ImportIFC43Command,
    InitializeBIMProductionRuntimeCommand,
    JoinBIMElementCommand,
    MirrorBIMElementCommand,
    MoveBIMElementCommand,
    OffsetBIMElementCommand,
    OptimizeBIMProjectCommand,
    PublishBIMPackageCommand,
    RefreshBIMInteroperabilityCommand,
    ReplaceBIMElementTypeCommand,
    RemoveBIMObjectCommand,
    RotateBIMElementCommand,
    RunBIMClashDetectionCommand,
    RunBIMModelCheckCommand,
    RunBIMModelValidationCommand,
    RunBIMDocumentationTakeoffCommand,
    RunBIMProductionRegressionCommand,
    RunBIMRuleCheckCommand,
    RunBIMQuantityTakeoffCommand,
    RunBIMValidationCommand,
    SplitBIMElementCommand,
    StartBIMAuthoringSessionCommand,
    SupportSlabByBeamCommand,
    UpdateBIMAuthoringContextCommand,
    UpdateBIMDocumentationSettingsCommand,
    UpdateBIMElementParametersCommand,
    UpdateIFC43Command,
    UpdateBIMPropertySetCommand,
    UpdateBIMSettingsCommand,
    ValidateBIMDocumentationCommand,
    ValidateBIMIntelligenceCommand,
    ValidateBIMRuntimeCommand,
)
from .gis_command import (
    AddGISLayerCommand,
    AddSurveyPointCommand,
    CreateGISProjectCommand,
    ImportGISFileCommand,
    RefreshGISIndexesCommand,
    RegisterGISCRSCommand,
    ValidateGISProjectCommand,
)
from .terrain_command import (
    CreateTerrainProjectCommand,
    EditTerrainSurfaceCommand,
    GenerateTerrainBodyCommand,
    GenerateTerrainContoursCommand,
    ImportTerrainFileCommand,
    RebuildTerrainSurfaceCommand,
    ValidateTerrainProjectCommand,
)
from .site_engineering_command import (
    AddSiteBoundaryCommand,
    AnalyzeSiteDrainageCommand,
    AnalyzeSiteSlopeCommand,
    ApplySiteGradingCommand,
    ComputeCutFillCommand,
    CreateSiteEngineeringProjectCommand,
    CreateSiteProfileCommand,
    CreateSiteSectionCommand,
    ValidateSiteEngineeringCommand,
)
from .infrastructure_command import (
    AddParcelCommand,
    AddRoadCommand,
    AddSurveyAlignmentCommand,
    AddUtilityNetworkCommand,
    CreateInfrastructureProjectCommand,
    EditRoadCommand,
    ImportGeoPackageCommand,
    ImportOpenStreetMapCommand,
    SynchronizeInfrastructureGISCommand,
    ValidateInfrastructureCommand,
)
from .ai_site_intelligence_command import (
    CreateAISiteIntelligenceProjectCommand,
    GenerateAISiteEngineeringReportsCommand,
    RunBuildabilityAnalysisCommand,
    RunConstraintIntelligenceCommand,
    RunEnvironmentalAnalysisCommand,
    RunSitePlanningCommand,
    ValidateAISiteIntelligenceCommand,
)
from .terrain_runtime_command import (
    CertifyTerrainCompatibilityCommand,
    CertifyTerrainReleaseCommand,
    CleanupTerrainRuntimeCommand,
    GenerateTerrainRuntimeVisualizationCommand,
    InitializeTerrainProductionRuntimeCommand,
    OptimizeTerrainRuntimeCommand,
    RunTerrainProductionRegressionCommand,
    ValidateTerrainRuntimeCommand,
)
from .integrated_design_command import (
    AddDesignReviewCheckpointCommand,
    BootstrapIntegratedPlatformRuntimeCommand,
    CertifyIntegratedPlatformRuntimeCommand,
    CoordinateAITaskCommand,
    CreateAutomationSessionCommand,
    CreateCoordinationIssueCommand,
    CreateDataExchangeSessionCommand,
    CreateDesignApprovalSessionCommand,
    CreateDesignReviewSessionCommand,
    ExecuteAutomationSessionCommand,
    CreateWorkflowSessionCommand,
    ExecuteWorkflowSessionCommand,
    GenerateAutomationAIVisualizationCommand,
    GenerateDesignCoordinationVisualizationCommand,
    GenerateDataExchangeVisualizationCommand,
    GenerateIntegratedVisualizationCommand,
    GenerateIntegratedPlatformRuntimeVisualizationCommand,
    GenerateWorkflowVisualizationCommand,
    InitializeAutomationAICoordinationCommand,
    InitializeDesignCoordinationCommand,
    InitializeDataExchangeManagerCommand,
    InitializeIntegratedDesignPlatformCommand,
    InitializeWorkflowOrchestratorCommand,
    MapIntegratedDependenciesCommand,
    QueryDataExchangeCommand,
    RefreshIntegratedProjectIndexCommand,
    RegisterUnifiedCommandsCommand,
    RecordDesignApprovalDecisionCommand,
    RunDesignClashDetectionCommand,
    RunIntegratedDesignRegressionCommand,
    ShutdownIntegratedPlatformRuntimeCommand,
    StartupIntegratedPlatformRuntimeCommand,
    SynchronizeDataExchangeCommand,
    UpdateCoordinationIssueCommand,
    ValidateAutomationAICoordinationCommand,
    ValidateDataExchangeCommand,
    ValidateDesignCoordinationCommand,
    ValidateIntegratedDesignPlatformCommand,
    ValidateIntegratedPlatformRuntimeCommand,
    ValidateWorkflowSessionCommand,
)
from .constraint_command import (
    CreateConstraintCommand,
    DeleteConstraintCommand,
    RenameConstraintCommand,
    UpdateConstraintCommand,
    EnableConstraintCommand,
)
