from engine.commands.command import Command


class AIParametricCADCommand(Command):
    """Undoable command sequence generated by the AI text-to-CAD planner."""

    def __init__(self, workspace, plan, commands):

        self.workspace = workspace
        self.plan = plan
        self.commands = list(commands or [])
        self.executed_commands = []
        self._product_state = None

    def execute(self):
        """Execute generated CAD commands in dependency order."""

        if self._product_state is None:
            self._product_state = self._capture_product_state()
        self.executed_commands = []
        for command in self.commands:
            command.execute()
            self.executed_commands.append(command)
        self._refresh_workspace()

    def undo(self):
        """Undo generated CAD commands in reverse dependency order."""

        for command in reversed(self.executed_commands):
            command.undo()
        self._restore_product_state()
        self._refresh_workspace()

    @property
    def name(self):
        """Return a readable history entry for the generated operation."""

        label = getattr(self.plan, "command_label", getattr(self.plan, "object_type", "Parametric CAD"))
        return f"AI Command: {label}"

    def _refresh_workspace(self):
        update_manager = getattr(self.workspace, "update_manager", None)
        if update_manager is not None:
            label = getattr(self.plan, "command_label", "AI command sequence")
            update_manager.queue_update(label, getattr(self.plan, "id", ""), "AI command sequence executed")

    def _capture_product_state(self):
        product = getattr(self.workspace, "product_manager", None)
        if product is None:
            return {}
        return {
            name: list(value)
            for name, value in vars(product).items()
            if isinstance(value, list)
        }

    def _restore_product_state(self):
        product = getattr(self.workspace, "product_manager", None)
        if product is None or self._product_state is None:
            return
        for name, value in self._product_state.items():
            setattr(product, name, list(value))
        if hasattr(product, "statistics"):
            product.statistics()
